// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12c2MDkC4TaxcAuncDg45u1svCENsR2A',
    appId: '1:84130873303:web:d5655a0c303559ba005592',
    messagingSenderId: '84130873303',
    projectId: 'beebsnotes',
    authDomain: 'beebsnotes.firebaseapp.com',
    storageBucket: 'beebsnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF61i8HSIvgD-0D_BKA1sLCbAMieJ_n8o',
    appId: '1:84130873303:android:a4064969449fe5db005592',
    messagingSenderId: '84130873303',
    projectId: 'beebsnotes',
    storageBucket: 'beebsnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMto5pqUOGwXZNE8Lstrixg-ufAlXwBIQ',
    appId: '1:84130873303:ios:deba22c18f668969005592',
    messagingSenderId: '84130873303',
    projectId: 'beebsnotes',
    storageBucket: 'beebsnotes.appspot.com',
    iosBundleId: 'com.example.beebnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMto5pqUOGwXZNE8Lstrixg-ufAlXwBIQ',
    appId: '1:84130873303:ios:deba22c18f668969005592',
    messagingSenderId: '84130873303',
    projectId: 'beebsnotes',
    storageBucket: 'beebsnotes.appspot.com',
    iosBundleId: 'com.example.beebnotes',
  );
}
